[rolling] Update maintainers - 2022-11-07
ros2/rmw_cyclonedds pull request #428
Opened 2022-11-07 23:26 UTC by audrow

This PR updates the maintainers and code owners. The new maintainers are:
* Ivan Paunovic (@ivanpauno)

This PR was made with https://github.com/audrow/update-ros2-repos.

2022-11-08 07:53 UTC, eboasson approved these changes
I'm fine with the change, but I do notice that I could be viewed as inconsistent with `package.xml`.

2022-11-08 13:20 UTC, clalancette requested changes
This one didn't remove Mich from the maintainers in the package.xml.

@eboasson You are right about it being inconsistent.  Would you be OK if we added your name into the CODEOWNERS file here?

2022-11-08 13:22 UTC, eboasson commented
> This one didn't remove Mich from the maintainers in the package.xml.
> 
> @eboasson You are right about it being inconsistent. Would you be OK if we added your name into the CODEOWNERS file here?

 I'm really happy I attended ROSCon: now I know again why I do it 😁 so yes, that's certainly ok!

2022-11-15 21:19 UTC, clalancette approved these changes

2022-11-15 21:33 UTC, merged